added folders models, routes, connection, controllers
jsots/Super_API_Back-End pull request #1
Opened 2023-04-28 14:39 UTC by lissashea

2023-04-28 20:19 UTC, jsots requested changes
Change instances of "Superhero" to Super and "Superheroes" to Supers. Note: there are cases where superheroes is spelled "superheros".

2023-04-29 15:20 UTC, lissashea commented
updated to characters / Character etc

2023-05-01 13:08 UTC, jsots approved these changes

2023-05-01 13:17 UTC, jsots approved these changes

2023-05-01 13:18 UTC, merged